apiVersion: apps/v1
kind: Deployment
metadata:
  name: p12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p12
  template:
    metadata:
      labels:
        app: p12
    spec:
      containers:
      - image: dorowu/ubuntu-desktop-lxde-vnc:focal-lxqt
        name: p12
        ports:
        - containerPort: 80
